version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    depends_on:
      - postgres
    ports:
      - "8080:8080"

    networks:
      - nw
  postgres:
    image: postgres:10

    ports:
      - "5433:5433"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    networks:
      - nw
networks:
  nw:
